"""Ammended table  column attribute

Revision ID: 117f27dd4ab3
Revises: 57a5f6bbceaf
Create Date: 2023-10-05 20:19:27.418294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f27dd4ab3'
down_revision = '57a5f6bbceaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doghouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.String(length=150), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    with op.batch_alter_table('doghouses', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###
